# Regression

In [ ]:
# Importing the required libraries

import numpy as np
import pandas as pd

In [ ]:
# Reading the dataset

df = pd.read_csv('/content/50_Startups.csv')

In [ ]:
# Visualize the data

df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
# Checking null values

df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
# Ckecking data type

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108 entries, 0 to 107
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        108 non-null    float64
 1   Administration   108 non-null    float64
 2   Marketing Spend  108 non-null    float64
 3   State            108 non-null    object 
 4   Profit           108 non-null    float64
dtypes: float64(4), object(1)
memory usage: 4.3+ KB


In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Initializing encoder

le = LabelEncoder()

In [ ]:
# Conerting string type into int type

df['State'] = le.fit_transform(df['State'])

In [ ]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [ ]:
# Split the data (Independent and dependent)

x = df.iloc[:,0:4].values
y = df.iloc[:,4:5].values

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Split the data (Training & testing)

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:
# Finding shapes od data

xtrain.shape, xtest.shape

((75, 4), (33, 4))

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
# Creating ANN skleton view

regressor = Sequential()
regressor.add(Dense(4,activation='relu'))
regressor.add(Dense(12,activation='relu'))
regressor.add(Dense(8,activation='relu'))
regressor.add(Dense(9,activation='relu'))
regressor.add(Dense(1,activation='linear'))

In [ ]:
# Compiling the ANN model

regressor.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [ ]:
# Training the model

regressor.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
8/8 [==============================] - 3s 4ms/step - loss: 16436102144.0000 - mse: 16436102144.0000
Epoch 2/300
8/8 [==============================] - 0s 3ms/step - loss: 14844260352.0000 - mse: 14844260352.0000
Epoch 3/300
8/8 [==============================] - 0s 3ms/step - loss: 13363758080.0000 - mse: 13363758080.0000
Epoch 4/300
8/8 [==============================] - 0s 3ms/step - loss: 12123712512.0000 - mse: 12123711488.0000
Epoch 5/300
8/8 [==============================] - 0s 3ms/step - loss: 11013340160.0000 - mse: 11013340160.0000
Epoch 6/300
8/8 [==============================] - 0s 4ms/step - loss: 9675458560.0000 - mse: 9675458560.0000
Epoch 7/300
8/8 [==============================] - 0s 3ms/step - loss: 8194734080.0000 - mse: 8194734080.0000
Epoch 8/300
8/8 [==============================] - 0s 3ms/step - loss: 6700616704.0000 - mse: 6700616704.0000
Epoch 9/300
8/8 [==============================] - 0s 3ms/step - loss: 5219987456.0000 - mse: 5219987456.0000


In [ ]:
# Testing the model

ypred = regressor.predict(xtest)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
# Finding accuracy

r2_score(ytest,ypred)*100

86.95962249339453

In [ ]:
# converting 2d into 1d

ypred.flatten()

array([ 37927.906, 130080.36 ,  83833.586, 180837.25 , 100004.47 ,
       125210.31 , 131765.52 , 171096.17 , 121759.81 ,  40179.98 ,
       107064.04 , 123777.875,  37927.906, 136705.28 ,  68193.95 ,
       134428.89 , 134428.89 , 106985.99 ,  70184.695, 146087.77 ,
       160495.55 , 164333.31 , 113197.15 , 165433.33 ,  95099.914,
       177969.1  , 129719.1  ,  15754.284,  90112.414, 152931.4  ,
        72742.95 , 207778.73 , 207737.12 ], dtype=float32)

In [ ]:
# Comparing actual data with predicted data

pd.DataFrame({'Actual value':ytest.flatten(),
              'Predicted value':ypred.flatten()}).head(10)

Actual value  Predicted value
0      64926.08     37927.906250
1     146121.95    130080.359375
2      90708.19     83833.585938
3     191050.39    180837.250000
4     108552.04    100004.468750
5     144259.40    125210.312500
6     124266.90    131765.515625
7     155752.60    171096.171875
8     126992.93    121759.812500
9      42559.73     40179.980469

In [ ]:
# Testing model with random data

regressor.predict([[1000,2354,1234,2]])

array([[1609.8904]], dtype=float32)

In [ ]:
# Testing model with random data

regressor.predict([[1000456,23235554,1232334,2]])

array([[7857300.5]], dtype=float32)

# Classification

In [ ]:
# Reading the dataset

data = pd.read_csv('/content/Breast Cancer Wisconsin (Diagnostic) Data Set.csv')

In [ ]:
# Visualize the data

data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [ ]:
# Checking null values

data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [ ]:
# Remove unwanted columns

data.drop(['id','Unnamed: 32'],axis=1,inplace=True)

In [ ]:
# Ckecking data type

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [ ]:
# Split the data (Independent and dependent)

x = data.drop('diagnosis',axis=1)
y = data['diagnosis']

In [ ]:
# Initializing encoder

le1 = LabelEncoder()

In [ ]:
# Converting string to int

y = le1.fit_transform(y)

In [ ]:
# Split the data (Training & testing)

xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
xtrain.shape

(455, 30)

In [ ]:
# Creating ANN skleton view

classification = Sequential()
classification.add(Dense(30,activation='relu'))
classification.add(Dense(128,activation='relu'))
classification.add(Dense(64,activation='relu'))
classification.add(Dense(32,activation='relu'))
classification.add(Dense(1,activation='sigmoid'))

NameError: ignored

In [ ]:
# Compiling the ANN model

classification.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
# Training the model

classification.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
46/46 [==============================] - 2s 4ms/step - loss: 4.4057 - accuracy: 0.7582
Epoch 2/300
46/46 [==============================] - 0s 3ms/step - loss: 0.6155 - accuracy: 0.8549
Epoch 3/300
46/46 [==============================] - 0s 3ms/step - loss: 0.5345 - accuracy: 0.8527
Epoch 4/300
46/46 [==============================] - 0s 3ms/step - loss: 1.1772 - accuracy: 0.7714
Epoch 5/300
46/46 [==============================] - 0s 3ms/step - loss: 0.8961 - accuracy: 0.8088
Epoch 6/300
46/46 [==============================] - 0s 3ms/step - loss: 0.5873 - accuracy: 0.8791
Epoch 7/300
46/46 [==============================] - 0s 3ms/step - loss: 0.5488 - accuracy: 0.8769
Epoch 8/300
46/46 [==============================] - 0s 3ms/step - loss: 0.4179 - accuracy: 0.8923
Epoch 9/300
46/46 [==============================] - 0s 3ms/step - loss: 0.3963 - accuracy: 0.8857
Epoch 10/300
46/46 [==============================] - 0s 3ms/step - loss: 0.4197 - accuracy: 0.9033
Epoch 11/

In [ ]:
# Testing the model

ypred = classification.predict(xtest)

In [ ]:
# Comparing actual data with predicted data

pd.DataFrame({'Actual value':ytest.flatten(),
              'Predicted value':np.round(ypred.flatten()).astype('int')}).head(20)

Actual value  Predicted value
0              1                1
1              0                0
2              0                0
3              0                0
4              0                0
5              0                0
6              0                0
7              0                0
8              0                0
9              0                0
10             0                0
11             0                0
12             0                0
13             0                1
14             0                0
15             1                1
16             0                0
17             1                1
18             1                1
19             1                1